---
sidebar: sidebar 
permalink: task-set-up-gcnv.html 
keywords: setup, set up, api, service account, requirements, permissions, google cloud netapp volumes, gcnv, bluexp. netapp console 
summary: 'La NetApp Console necessita dell"accesso all"API Google Cloud NetApp Volumes e delle autorizzazioni appropriate tramite un account di servizio Google Cloud.' 
---
= Configurare Google Cloud NetApp Volumes
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
La NetApp Console necessita delle autorizzazioni appropriate tramite un account di servizio Google Cloud.

Completa le seguenti attività affinché NetApp Console possa accedere al tuo progetto Google Cloud.


NOTE: Per queste attività puoi utilizzare la console Google Cloud o la CLI gcloud. Per utilizzare la CLI gcloud, devi link:https://cloud.google.com/sdk/docs/install-sdk["installato la CLI di Google Cloud"^] prima.

* Se non disponi già di un account di servizio, creane uno nuovo.
* Concedi l'accesso per impersonare qualcuno.
* Concedi il ruolo IAM nel progetto condiviso.




== Configurare un account di servizio

. Nella console di Google Cloud, https://console.cloud.google.com/iam-admin/serviceaccounts["vai alla pagina Account di servizio"^] .
. Fai clic su *Seleziona un progetto*, scegli il progetto e fai clic su *Apri*.
. Per creare un account di servizio, procedere come segue:
+
.. Fare clic su *Crea account di servizio*.
.. Inserisci il nome dell'account del servizio (nome visualizzato) e la descrizione.
+
Google Cloud Console genera un ID account di servizio basato su questo nome.  Se necessario, modifica l'ID: non potrai più modificarlo in seguito.

.. Fare clic su *Crea e continua*.
.. Dall'elenco Ruolo, seleziona il ruolo *Amministratore Google Cloud NetApp Volumes * o *Visualizzatore Google Cloud NetApp *.
.. Selezionare *Continua*.
+
In alternativa, è possibile assegnare il ruolo utilizzando la CLI di gcloud:

+
[source, cli]
----
gcloud projects add-iam-policy-binding <YOUR_PROJECT_ID> --member="serviceAccount:<YOUR_SA_EMAIL>" --role="roles/netapp.admin"
----
.. Concedi l'accesso di impersonificazione a questo account di servizio: credentials-sa@wf-production-netapp.iam.gserviceaccount.com. Per i dettagli, vedere https://cloud.google.com/iam/docs/create-short-lived-credentials-direct#sa-credentials-jwt["Crea un JSON Web Token (JWT) autofirmato"^] .
+
L'account di servizio di proprietà di NetApp viene utilizzato per richiedere un token di accesso di breve durata che consente di agire come tale account di servizio senza dover accedere alla sua chiave privata.

+
In alternativa, è possibile concedere l'accesso per impersonare utilizzando la CLI di gcloud:

+
[source, cli]
----
gcloud iam service-accounts add-iam-policy-binding <YOUR_SA_EMAIL> --member="serviceAccount:credentials-sa@wf-production-netapp.iam.gserviceaccount.com" --role="roles/iam.serviceAccountTokenCreator" --project=<YOUR_PROJECT_ID>
----
.. Fare clic su *FATTO* in fondo alla pagina e procedere al passaggio successivo.






== VPC condivisa

In ogni progetto GCP aggiuntivo che utilizzerà l'account di servizio, procedere come segue:

. Nella pagina _IAM_, seleziona il progetto host VPC condiviso dal menu a discesa del progetto.
. Fare clic su *Aggiungi principale*.
. Nel campo Nuovi principali, inserisci l'indirizzo email del tuo account di servizio.
. Dal menu a discesa Seleziona un ruolo, scegli il ruolo *Amministratore Google Cloud NetApp Volumes *.
. Fare clic su *Salva*.
+
In alternativa, è possibile aggiungere il binding della policy IAM utilizzando la CLI di gcloud:

+
[source, cli]
----
gcloud projects add-iam-policy-binding <SHARED_VPC_HOST_PROJECT_ID> --member="serviceAccount:<YOUR_SA_EMAIL>" --role="roles/netapp.admin"
----


Per i passaggi dettagliati, fare riferimento alla documentazione di Google Cloud:

* link:https://cloud.google.com/iam/docs/creating-managing-service-accounts["Creazione e gestione degli account di servizio"^]
* link:https://cloud.google.com/iam/docs/roles-permissions/netapp["Ruoli e autorizzazioni Google Cloud NetApp Volumes"^]
* link:https://cloud.google.com/iam/docs/granting-changing-revoking-access["Concedere, modificare e revocare l'accesso alle risorse"^]




== Risoluzione dei problemi

Se si verifica un errore, potrebbe essere applicata la policy *iam.disableCrossProjectServiceAccountUsage*.  Per risolvere questo problema, procedi come segue:

. Nella console di Google Cloud, vai a https://console.cloud.google.com/iam-admin/orgpolicies["Pagina delle politiche dell'organizzazione"^] .
. Trova il criterio *Disabilita l'utilizzo dell'account di servizio tra progetti* e disattivalo.


.Cosa succederà ora?
link:task-add-roles.html["Assegnare i ruoli Google Cloud NetApp Volumes"].
