---
sidebar: sidebar 
permalink: task-set-up-gcnv.html 
keywords: setup, set up, api, service account, requirements, permissions, google cloud netapp volumes, gcnv, bluexp. netapp console 
summary: 'La console NetApp necessita dell"accesso all"API Google Cloud NetApp Volumes e delle autorizzazioni appropriate tramite un account di servizio Google Cloud.' 
---
= Configurare Google Cloud NetApp Volumes
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
La console NetApp necessita delle autorizzazioni appropriate tramite un account di servizio Google Cloud.



== Configurare un account di servizio

Completa le seguenti attività affinché la console NetApp possa accedere al tuo progetto Google Cloud:

* Se non disponi già di un account di servizio, creane uno nuovo.
* Aggiungi il membro dell'account di servizio al tuo progetto e assegnagli ruoli specifici (autorizzazioni).
* Crea e scarica una coppia di chiavi per l'account di servizio utilizzato per l'autenticazione su Google.


.Passi
. Nella console di Google Cloud, https://console.cloud.google.com/iam-admin/serviceaccounts["vai alla pagina Account di servizio"^] .
. Fai clic su *Seleziona un progetto*, scegli il progetto e fai clic su *Apri*.
. (Facoltativo) Per creare un account di servizio, procedere come segue:
+
.. Fare clic su *Crea account di servizio*.
.. Inserisci il nome dell'account del servizio (nome visualizzato) e la descrizione.
+
Google Cloud Console genera un ID account di servizio basato su questo nome.  Se necessario, modifica l'ID: non potrai più modificarlo in seguito.

.. Per impostare subito i controlli di accesso, fare clic su *Crea* e poi su *FATTO* in fondo alla pagina, quindi procedere al passaggio successivo.


. Dalla pagina _IAM_ clicca su *Aggiungi* e compila i campi nella pagina _Aggiungi membri_:
+
.. Nel campo Nuovi membri, immettere l'ID completo dell'account di servizio.
+
Ad esempio: \user1-service-account-gcnv@project1.iam.gserviceaccount.com

.. Aggiungi uno di questi ruoli:
+
*** _Amministratore di Google Cloud NetApp Volumes_ OPPURE
*** _Visualizzatore volumi Google Cloud NetApp


.. Fare clic su *Salva*.


. Fare clic sul nome dell'account di servizio, quindi nella pagina _Dettagli account di servizio_ fare clic su *Aggiungi chiave* e quindi su *Crea nuova chiave*.
. Selezionare *JSON* come tipo di chiave e fare clic su *Crea*.
+
Facendo clic su *Crea* la nuova coppia di chiavi pubblica/privata verrà generata e scaricata sul tuo sistema.  Funge da unica copia della chiave privata.  Conserva questo file in modo sicuro perché può essere utilizzato per l'autenticazione come account di servizio.



Per i passaggi dettagliati, fare riferimento alla documentazione di Google Cloud:

* link:https://cloud.google.com/iam/docs/roles-permissions/netapp["Ruoli e autorizzazioni Google Cloud NetApp Volumes"^]
* link:https://cloud.google.com/iam/docs/creating-managing-service-accounts["Creazione e gestione degli account di servizio"^]
* link:https://cloud.google.com/iam/docs/granting-changing-revoking-access["Concedere, modificare e revocare l'accesso alle risorse"^]
* link:https://cloud.google.com/iam/docs/creating-managing-service-account-keys["Creazione e gestione delle chiavi dell'account di servizio"^]

