---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, bugs, limitations, known issues, enhancements, fixes' 
summary: Scopri le novità sul supporto di Google Cloud NetApp Volumes nella NetApp Console. 
---
= Cosa c'è di nuovo
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Scopri le novità sul supporto di Google Cloud NetApp Volumes nella NetApp Console.



== 06 ottobre 2025



=== BlueXP è ora NetApp Console

NetApp Console, basata sulle fondamenta BlueXP migliorate e ristrutturate, offre una gestione centralizzata dello storage NetApp e NetApp Data Services in ambienti on-premise e cloud di livello aziendale, offrendo informazioni in tempo reale, flussi di lavoro più rapidi e un'amministrazione semplificata, il tutto in modo altamente sicuro e conforme.

Per i dettagli su cosa è cambiato, vedere illink:https://docs.netapp.com/us-en/bluexp-relnotes/index.html["Note sulla versione NetApp Console"] .



== 21 luglio 2025



=== Supporto per Google Cloud NetApp Volumes in BlueXP

Ora puoi gestire Google Cloud NetApp Volumes direttamente da BlueXP:

* Aggiungere un ambiente di lavoro.
* Visualizza i volumi.
* Rimuovere gli ambienti di lavoro.

